ccflags-y += -Idrivers/media/platform/msm/camera_v2
ccflags-y += -Idrivers/media/platform/msm/camera_v2/common
ccflags-y += -Idrivers/media/platform/msm/camera_v2/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2/sensor/cci
obj-$(CONFIG_MSM_EEPROM) += zte_eeprom.o
obj-$(CONFIG_MSM_EEPROM) += common_eeprom.o
obj-$(CONFIG_OV16B10_031_EEPROM) += ov16b10_031_eeprom.o
obj-$(CONFIG_S5K4H7_127_EEPROM) += s5k4h7_127_eeprom.o
